### ISSUE TITLE
linkchercker is not available in the last Ubuntu LTS (focal)

### ISSUE THREAD

**Issue by oupala** [linkchecker/linkchecker#493] opened 2020-08-24 12:52 UTC
## Steps to reproduce

 1. to to https://packages.ubuntu.com/eoan/linkchecker
 2. see that the linkchecker debian package is not available after eoan

## Actual result

linkchecker is not available in the last Ubuntu LTS (focal)

## Expected result

linkchecker is available in the last Ubuntu LTS (focal)

## Environment

 * Operating system: Ubuntu eoan / focal
 * Linkchecker version: 9.4
 * Python version: 
 * Install method: 
 * Site URL:

**Comment by cjmayo** [comment] 2020-08-24 18:32
Not directly a project issue, indirectly I suppose a duplicate of #359.

**Closed by cjmayo** 2020-08-24 18:32 UTC
Labels: duplicate

**Comment by robations** [comment] 2021-03-11 11:58
@cjmayo might be worth changing the docs though, it says it's available for Ubuntu (https://github.com/linkchecker/linkchecker/blob/master/doc/install.txt)

**Comment by oupala** [comment] 2021-03-12 07:57
It seems that linkcheck is now [available in the forthcoming Ubuntu hirsute](https://packages.ubuntu.com/search?suite=all&searchon=names&keywords=linkchecker).
