### ISSUE TITLE
Unable to check page using a proxy

### ISSUE THREAD

**Issue by alex4200** [linkchecker/linkchecker#346] opened 2020-03-04 10:20 UTC
## Summary

`linkchecker` is unable to connect to a webpage via proxy.

## Actual result

Using `linkchecker` I get an error (see details below):

```
Result     Error: ConnectionError: HTTPSConnectionPool(host='portal.bluebrain.epfl.ch', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f23d43bae10>: Failed to establish a ne...
```

## Expected result

It is possible to establish a connection.

## Environment

 * Operating system:Linux bbpcj048.bbp.epfl.ch 3.10.0-957.12.1.el7.x86_64 #1 SMP Wed Mar 20 11:34:37 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 * Linkchecker version: LinkChecker 9.4.0 released xx.xx.xxxx
 * Python version: 2.7.5
 * Install method: pip install --user git+https://github.com/linkchecker/linkchecker.git

## Logs

```
+ linkchecker --verbose --check-extern https://portal.bluebrain.epfl.ch/
LinkChecker 9.4.0              Copyright (C) 2000-2014 Bastian Kleineidam
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it
under certain conditions. Look at the file `LICENSE' within this
distribution.
Get the newest version at http://wummel.github.io/linkchecker/
Write comments and bugs to https://github.com/wummel/linkchecker/issues
Support this project at http://wummel.github.io/linkchecker/donations.html

Start checking at 2020-03-04 11:18:31+002

URL        `https://portal.bluebrain.epfl.ch/'
Real URL   https://portal.bluebrain.epfl.ch/
Check time 0.283 seconds
Info       Using proxy `http://bbpproxy.epfl.ch:80/'.
Result     Error: ConnectionError: HTTPSConnectionPool(host='portal.bluebrain.epfl.ch', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa8b459a8d0>: Failed to establish a ne...

URL        `https://portal.bluebrain.epfl.ch/sitemap.xml'
Parent URL https://portal.bluebrain.epfl.ch/, line 1
Real URL   https://portal.bluebrain.epfl.ch/sitemap.xml
Check time 0.562 seconds
Info       Using proxy `http://bbpproxy.epfl.ch:80/'.
Result     Error: ConnectionError: HTTPSConnectionPool(host='portal.bluebrain.epfl.ch', port=443): Max retries exceeded with url: /sitemap.xml (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa8b459a350>: Failed to est...
 1 thread active,     0 links queued,    2 links in   3 URLs checked, runtime 1 seconds
URL        `https://portal.bluebrain.epfl.ch/news-sitemap.xml'
Parent URL https://portal.bluebrain.epfl.ch/, line 2
Real URL   https://portal.bluebrain.epfl.ch/news-sitemap.xml
Check time 0.837 seconds
Info       Using proxy `http://bbpproxy.epfl.ch:80/'.
Result     Error: ConnectionError: HTTPSConnectionPool(host='portal.bluebrain.epfl.ch', port=443): Max retries exceeded with url: /news-sitemap.xml (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7fa8b459aad0>: Failed t...

Statistics:
Downloaded: 0B.
Content types: 0 image, 0 text, 0 video, 0 audio, 0 application, 0 mail and 3 other.
URL lengths: min=33, max=49, avg=42.
```

## Other notes

The command runs inside a jenkins job and uses the given proxies. I am able to `wget` the site, so there is no connection problem. It must be a bug in `linkchecker`.

**Comment by wadefelix** [comment] 2021-03-04 07:40
same problem.
not all failed, but many failed.

**Comment by vyshnavarajesh** [comment] 2021-03-09 12:24
Hi alex4200, can you please share the command to run linkchecker on proxy

**Comment by cjmayo** [comment] 2021-12-10 19:50
Looks like a duplicate of #258.
```
URL        `https://portal.bluebrain.epfl.ch/'
Info       Using proxy `http://bbpproxy.epfl.ch:80/'.
```
See the latest comment there for what is hopefully a fix.

**Closed by cjmayo** 2021-12-10 19:50 UTC
Labels: duplicate
