### ISSUE TITLE
Support for large amount of html documentation on Win64 systems.

### ISSUE THREAD

**Issue by jmichelberger** [linkchecker/linkchecker#107] opened 2017-11-07 15:47 UTC
I am using LinkChecker to check a quite large documentation packet (~6,5GB) hosted on my disk.

LinkChecker works very well, but after a while it starts printing stack traces to console out.

The size of the linkchecker.exe process in memory is about the magic WOW64 2GB limit of a 32Bit App on 64Bit Windows.
 I/O Bytes of linkchecker.exe in ProcessExplorer suggest that only 400MB of data was transferred to linkchecker.exe.
 That is less than 10% of my documentation packet.
 16 threads active, 480080 links queued, 1110443 links in 7892 URLs checked, Laufzeit 32 Minuten, 13 Sekunden
 Get:
 MemoryError: out of memory
 And several follow up Stack Traces.

Transferred from https://github.com/wummel/linkchecker/issues/606.
See there for more comments...

**Comment by anarcat** [comment] 2017-11-07 15:58
youch, that's quite massive! i'm not sure how to solve this, but I've always felt that the algorithms could/should be tweak to traverse the link tree "breadth-first" instead of piling up links like that... i would assume that here, what is crashing the RAM are the "480080 links queued" - if we could tweak the core algorithm to try and reduce that number instead of raising it, maybe that could be worked around.

that said, an obvious fix would be to run linkchecker in 64 bits... any reason why this can't be done? I'm not familiar with Windows apps so I'm not sure why you're running in 32 bits...

**Comment by jmichelberger** [comment] 2017-11-07 19:09
Hi there,

Yes of course this is a large bunch of links to check. Running in 32 bit is
not the intended way, it's that the wummel 9.3 link checker build for
Windows is 32bit. Maybe you can change that and provide 32bit and 64bit
builds. I digged a bit into the code and stopped after finding additional
dlls which are maybe part of the distribution or runtime. And there are no
64bit dlls around. 32bit exe can load 32bit only, same for 64bit. So I
stopped my investigation and wrote the initial GitHub issue. I even not
tried to find an entry point to start the python scripts with a 64bit
python.

There is an additional issue in wummel GitHub describing a mutex glitch
between link cache an HTML scanner and link check engine, so the occurrence
of same link in different HTML sources can be added multiple times to check
engine queue, which leads to duplicate checks. Not God for memory...

Hope that helps...

Thanks
Jörg Michelberger

Am 07.11.2017 16:58 schrieb "anarcat" <notifications@github.com>:

youch, that's quite massive! i'm not sure how to solve this, but I've
always felt that the algorithms could/should be tweak to traverse the link
tree "breadth-first" instead of piling up links like that... i would assume
that here, what is crashing the RAM are the "480080 links queued" - if we
could tweak the core algorithm to try and reduce that number instead of
raising it, maybe that could be worked around.

that said, an obvious fix would be to run linkchecker in 64 bits... any
reason why this can't be done? I'm not familiar with Windows apps so I'm
not sure why you're running in 32 bits...

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/linkcheck/linkchecker/issues/107#issuecomment-342528941>,
or mute the thread

**Comment by cjmayo** [comment] 2020-08-14 18:17
Looks like a duplicate of #65. No current Windows binaries.

**Closed by cjmayo** 2020-08-14 18:17 UTC
Labels: enhancement
