### ISSUE TITLE
availability of linkchecker 10 in Docker Hub

### ISSUE THREAD

**Issue by oupala** [linkchecker/linkchecker#537] opened 2021-04-30 07:26 UTC
## Summary

linkchecker has been published in version 10 but docker image from docker hub is still in version 9.4.0

## Steps to reproduce

 1. `git pull linkchercker/linkchecker`
 2. `docker run -it --rm linkchecker/linkchecker -v`
 3. look at the console output:

> LinkChecker 9.4.0              Copyright (C) 2000-2014 Bastian Kleineidam

## Actual result

Look at the console output:

> LinkChecker 9.4.0              Copyright (C) 2000-2014 Bastian Kleineidam

## Expected result

Look at the console output:

> LinkChecker 10.0.1              Copyright (C) 2000-2021 Bastian Kleineidam

## Other notes

I know that the README file is telling that the docker image is out-of-date:

> The Docker images are out-of-date, pip installation is the only currently recommended method.

The problem is hence already known. But I think it would be great if we can discuss this issue and understand why is the docker image not up-to-date.

**Comment by phaer** [comment] 2021-06-17 11:53
> But I think it would be great if we can discuss this issue and understand why is the docker image not up-to-date.

As you mentioned in #538 contents of the image differ between a local build and the one on docker.com. And there seem to be no build instructions for a docker image in travis-ci & github action configuration, so my best guess is that that image was built and uploaded by someone manually until it wasn't.

I am no contributor to this project, but if a docker image is deemed necessary at all, i guess the best thing would be to update automatically via CI.

**Comment by alberto56** [comment] 2021-09-08 19:53
> best thing would be to update automatically via CI.

As mentioned in #538, I maintain such as an automatically updated CI image (it automatically updates weekly):

```
$ docker run --rm dcycle/broken-link-checker:2 --version
WARNING linkcheck.check 2021-09-08 19:51:27,201 MainThread Running as root user; dropping privileges by changing user to nobody.
LinkChecker 10.0.1 released 29.1.2021
Copyright (C) 2000-2016 Bastian Kleineidam, 2010-2021 LinkChecker Authors

```

You might want to link to my project if you so desire instead of manually maintaining your own docker image.

**Comment by oupala** [comment] 2021-09-08 19:59
Maybe a better option would be that your image becomes part of the official linkchecker project.

Would you agree to embed Dockerfile, CI and Docker image into the official linkchecker repository?

**Comment by alberto56** [comment] 2021-09-08 20:12
@oupala do you mean the Docker repository or the code repository? If you mean the code repository, I think conceptually Linkchecker itself, and the Dockerization of Linkchecker, should be two separate codebases and managed separately.

**Comment by phaer** [comment] 2021-09-09 07:12
@alberto56 There's currently an out-dated Docker image in this (upstream) repo, so that should be at least deleted if a second repo in the linkchecker org would be needed. Personally, I see no harm with updating it in this repo? But I am just a user ;)

**Comment by oupala** [comment] 2021-09-09 21:56
I agree with @phaer that updating the existing Dockerfile should be ok. In a perfect conceptual world, I also do agree with @alberto56 that Linkchecker itself, and the Dockerization of Linkchecker, should be two separate codebases and managed separately. But in this case, creating a separate git repo for only one file seems too much to me.

I mainly think that the existing Dockerfile should be updating with your version, and that the image built from this new Dockerfile should be [pushed to the official Linkchercker image](https://hub.docker.com/r/linkchecker/linkchecker).

**Comment by alberto56** [comment] 2021-09-10 03:19
@oupala it seems to be a recurring pattern that one Docker image maps to one github repo, often separate from the project it contains.

For example, the https://hub.docker.com/_/drupal official image corresponds to the https://github.com/docker-library/drupal github repo.

If you agree, I can move https://github.com/dcycle/docker-broken-link-checker to a new repository at https://github.com/linkchecker/docker-linkchecker.

Then I could have my continuous integration server push weekly to https://hub.docker.com/r/linkchecker/linkchecker instead of https://hub.docker.com/r/dcycle/broken-link-checker

That would require you to provide me with write access to a new https://github.com/linkchecker/docker-linkchecker and access to the https://hub.docker.com/r/linkchecker account on the Docker Hub.

Let me know if this makes sense to you.

**Comment by oupala** [comment] 2021-09-10 07:14
see also #538

**Comment by oupala** [comment] 2021-09-10 07:17
I think that your proposal makes sense. But unfortunately, I am not a maintainer of linkchecker. I'm just a user and a contributor, as you.

Maybe @cjmayo could have an opinion and get into the thread.

**Comment by cjmayo** [comment] 2021-11-25 19:52
Yes, it needs automating. Please have a look at PR #576. This would be updated on every push to master.

First attempt is already available.
https://github.com/linkchecker/linkchecker/pkgs/container/linkchecker

Staying within GitHub offers advantages, including not having to deal with authentication and tying to an individual user account.

To keep the integrity of the record this ticket is basically a duplicate of #264 (with some more ideas!).

**Comment by cjmayo** [comment] 2021-11-29 20:06
Now live, rolling tag changed from master to latest, plus git checksum tags.

**Closed by cjmayo** 2021-11-29 20:06 UTC
Labels: duplicate

**Comment by oupala** [comment] 2021-11-30 22:06
It should be made clearer that the Docker image of linkchecker is available on GitHub registry, as this registry is not widely known.

It took me a while to understand that the Docker image was hosted by GitHub, I was looking at DockerHub and I was seing that the image had not been updated for many years...
