### ISSUE TITLE
"Invalid IPv6 URL" error in linkchecker

### ISSUE THREAD

**Issue by sebras** [linkchecker/linkchecker#148] opened 2018-04-17 17:45 UTC
I recently encountered an "Invalid IPv6 URL" error in linkchecker that I can repeat every time.

I got hold of link checker by:
```
git clone https://github.com/linkcheck/linkchecker.git /tmp/linkchecker.src
```

and then build it like so:
```
cd /tmp/linkchecker.src
python setup.py sdist --manifest-only
python setup.py build
export PYTHONPATH=/tmp/linkchecker/lib/python
export PATH=/tmp/linkchecker/bin:$PATH
python setup.py install --home /tmp/linkchecker
```
For your information I'm running this on an up to date Debian/testing box.

Next I ran
```
linkchecker -Fhtml -r=1 --verbose https://ghostscript.com/irclogs/2014/07/30.html
```

This resulted in the following output:
```
INFO linkcheck.cmdline 2018-04-18 01:42:59,636 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
LinkChecker 9.4.0              Copyright (C) 2000-2014 Bastian Kleineidam
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it
under certain conditions. Look at the file `LICENSE' within this
distribution.
Get the newest version at http://wummel.github.io/linkchecker/
Write comments and bugs to https://github.com/wummel/linkchecker/issues
Support this project at http://wummel.github.io/linkchecker/donations.html

Start checking at 2018-04-18 01:42:59+008
 1 thread active,     0 links queued,    0 links in   1 URL checked, runtime 1 seconds


********** Oops, I did it again. *************

You have found an internal error in LinkChecker. Please write a bug report
at https://github.com/wummel/linkchecker/issues
and include the following information:
- the URL or file you are testing
- the system information below

When using the commandline client:
- your commandline arguments and any custom configuration files.
- the output of a debug run with option "-Dall"

Not disclosing some of the information above due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

Traceback (most recent call last):
  File "/tmp/linkchecker/lib/python/LinkChecker-9.4.0-py2.7-linux-x86_64.egg/linkcheck/director/checker.py", line 104, in check_url
    line: self.check_url_data(url_data)
    locals:
      self = <local> <Checker(CheckThread-https://ghostscript.com/irclogs/2014/07/30.html, started 140446560040704)>
      self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-https://ghostscript.com/irclogs/2014/07/30.html, started 140446560040704)>>
      url_data = <local> <https link, base_url=u'https://ghostscript.com/irclogs/2014/07/30.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://ghostscript.com/irclogs/2014/07/30.html>
  File "/tmp/linkchecker/lib/python/LinkChecker-9.4.0-py2.7-linux-x86_64.egg/linkcheck/director/checker.py", line 120, in check_url_data
    line: check_url(url_data, self.logger)
    locals:
      check_url = <global> <function check_url at 0x7fbc47f97050>
      url_data = <local> <https link, base_url=u'https://ghostscript.com/irclogs/2014/07/30.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://ghostscript.com/irclogs/2014/07/30.html>
      self = <local> <Checker(CheckThread-https://ghostscript.com/irclogs/2014/07/30.html, started 140446560040704)>
      self.logger = <local> <linkcheck.director.logger.Logger object at 0x7fbc43fb09d0>
  File "/tmp/linkchecker/lib/python/LinkChecker-9.4.0-py2.7-linux-x86_64.egg/linkcheck/director/checker.py", line 64, in check_url
    line: parser.parse_url(url_data)
    locals:
      parser = <global> <module 'linkcheck.parser' from '/tmp/linkchecker/lib/python/LinkChecker-9.4.0-py2.7-linux-x86_64.egg/linkcheck/parser/__init__.pyc'>
      parser.parse_url = <global> <function parse_url at 0x7fbc47f8d5f0>
      url_data = <local> <https link, base_url=u'https://ghostscript.com/irclogs/2014/07/30.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://ghostscript.com/irclogs/2014/07/30.html>
  File "/tmp/linkchecker/lib/python/LinkChecker-9.4.0-py2.7-linux-x86_64.egg/linkcheck/parser/__init__.py", line 41, in parse_url
    line: globals()[funcname](url_data)
    locals:
      globals = <builtin> <built-in function globals>
      funcname = <local> 'parse_html', len = 10
      url_data = <local> <https link, base_url=u'https://ghostscript.com/irclogs/2014/07/30.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://ghostscript.com/irclogs/2014/07/30.html>
  File "/tmp/linkchecker/lib/python/LinkChecker-9.4.0-py2.7-linux-x86_64.egg/linkcheck/parser/__init__.py", line 50, in parse_html
    line: find_links(url_data, url_data.add_url, linkparse.LinkTags)
    locals:
      find_links = <global> <function find_links at 0x7fbc47f8da28>
      url_data = <local> <https link, base_url=u'https://ghostscript.com/irclogs/2014/07/30.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://ghostscript.com/irclogs/2014/07/30.html>
      url_data.add_url = <local> <bound method HttpUrl.add_url of <https link, base_url=u'https://ghostscript.com/irclogs/2014/07/30.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://ghostscript.com/irclogs/2014/07/30.html>>
      linkparse = <global> <module 'linkcheck.htmlutil.linkparse' from '/tmp/linkchecker/lib/python/LinkChecker-9.4.0-py2.7-linux-x86_64.egg/linkcheck/htmlutil/linkparse.pyc'>
      linkparse.LinkTags = <global> {'frame': [u'src', u'longdesc'], 'a': [u'href'], 'meta': [u'content', u'href'], 'iframe': [u'src', u'longdesc'], 'tr': [u'background'], 'del': [u'cite'], 'ilayer': [u'background'], 'input': [u'src', u'usemap', u'formaction'], 'body': [u'background'], 'object': [u'classid', u'data', u'archive', u'..., len = 35
  File "/tmp/linkchecker/lib/python/LinkChecker-9.4.0-py2.7-linux-x86_64.egg/linkcheck/parser/__init__.py", line 128, in find_links
    line: parser.feed(url_data.get_content())
    locals:
      parser = <local> <linkcheck.HtmlParser.htmlsax.parser object at 0x7fbc404e1470>
      parser.feed = <local> <built-in method feed of linkcheck.HtmlParser.htmlsax.parser object at 0x7fbc404e1470>
      url_data = <local> <https link, base_url=u'https://ghostscript.com/irclogs/2014/07/30.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://ghostscript.com/irclogs/2014/07/30.html>
      url_data.get_content = <local> <bound method HttpUrl.get_content of <https link, base_url=u'https://ghostscript.com/irclogs/2014/07/30.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://ghostscript.com/irclogs/2014/07/30.html>>
  File "/tmp/linkchecker/lib/python/LinkChecker-9.4.0-py2.7-linux-x86_64.egg/linkcheck/htmlutil/linkparse.py", line 231, in start_element
    line: self.parse_tag(tag, attr, value, name, base)
    locals:
      self = <local> <linkcheck.htmlutil.linkparse.LinkFinder object at 0x7fbc43561dd0>
      self.parse_tag = <local> <bound method LinkFinder.parse_tag of <linkcheck.htmlutil.linkparse.LinkFinder object at 0x7fbc43561dd0>>
      tag = <local> u'a'
      attr = <local> u'href'
      value = <local> u'http://www.ghostscript.com]', len = 27
      name = <local> u'http://www.ghostscript.com]', len = 27
      base = <local> u'http://ghostscript.com/irclogs/', len = 31
  File "/tmp/linkchecker/lib/python/LinkChecker-9.4.0-py2.7-linux-x86_64.egg/linkcheck/htmlutil/linkparse.py", line 277, in parse_tag
    line: self.found_url(value, name, base)
    locals:
      self = <local> <linkcheck.htmlutil.linkparse.LinkFinder object at 0x7fbc43561dd0>
      self.found_url = <local> <bound method LinkFinder.found_url of <linkcheck.htmlutil.linkparse.LinkFinder object at 0x7fbc43561dd0>>
      value = <local> u'http://www.ghostscript.com]', len = 27
      name = <local> u'http://www.ghostscript.com]', len = 27
      base = <local> u'http://ghostscript.com/irclogs/', len = 31
  File "/tmp/linkchecker/lib/python/LinkChecker-9.4.0-py2.7-linux-x86_64.egg/linkcheck/htmlutil/linkparse.py", line 283, in found_url
    line: column=self.parser.last_column(), name=name, base=base)
    locals:
      column = <not found>
      self = <local> <linkcheck.htmlutil.linkparse.LinkFinder object at 0x7fbc43561dd0>
      self.parser = <local> <linkcheck.HtmlParser.htmlsax.parser object at 0x7fbc404e1470>
      self.parser.last_column = <local> <built-in method last_column of linkcheck.HtmlParser.htmlsax.parser object at 0x7fbc404e1470>
      name = <local> u'http://www.ghostscript.com]', len = 27
      base = <local> u'http://ghostscript.com/irclogs/', len = 31
  File "/tmp/linkchecker/lib/python/LinkChecker-9.4.0-py2.7-linux-x86_64.egg/linkcheck/checker/urlbase.py", line 668, in add_url
    line: page=page, name=name, parent_content_type=self.content_type)
    locals:
      page = <local> 0
      name = <local> u'http://www.ghostscript.com]', len = 27
      parent_content_type = <not found>
      self = <local> <https link, base_url=u'https://ghostscript.com/irclogs/2014/07/30.html', parent_url=None, base_ref=None, recursion_level=0, url_connection=None, line=0, column=0, page=0, name=u'', anchor=u'', cache_url=https://ghostscript.com/irclogs/2014/07/30.html>
      self.content_type = <local> 'text/html', len = 9
  File "/tmp/linkchecker/lib/python/LinkChecker-9.4.0-py2.7-linux-x86_64.egg/linkcheck/checker/__init__.py", line 125, in get_url_from
    line: line=line, column=column, page=page, name=name, extern=extern)
    locals:
      line = <local> 32
      column = <local> 142
      page = <local> 0
      name = <local> u'http://www.ghostscript.com]', len = 27
      extern = <local> None
  File "/tmp/linkchecker/lib/python/LinkChecker-9.4.0-py2.7-linux-x86_64.egg/linkcheck/checker/urlbase.py", line 131, in __init__
    line: self.check_syntax()
    locals:
      self = <local> <http link, base_url=u'http://www.ghostscript.com]', parent_url=u'https://ghostscript.com/irclogs/2014/07/30.html', base_ref=u'http://ghostscript.com/irclogs/', recursion_level=1, url_connection=None, line=32, column=142, page=0, name=u'http://www.ghostscript.com]', anchor=None, cache_url=None>
      self.check_syntax = <local> <bound method HttpUrl.check_syntax of <http link, base_url=u'http://www.ghostscript.com]', parent_url=u'https://ghostscript.com/irclogs/2014/07/30.html', base_ref=u'http://ghostscript.com/irclogs/', recursion_level=1, url_connection=None, line=32, column=142, page=0, name=u'http://www.ghostscript...
  File "/tmp/linkchecker/lib/python/LinkChecker-9.4.0-py2.7-linux-x86_64.egg/linkcheck/checker/urlbase.py", line 336, in check_syntax
    line: self.build_url()
    locals:
      self = <local> <http link, base_url=u'http://www.ghostscript.com]', parent_url=u'https://ghostscript.com/irclogs/2014/07/30.html', base_ref=u'http://ghostscript.com/irclogs/', recursion_level=1, url_connection=None, line=32, column=142, page=0, name=u'http://www.ghostscript.com]', anchor=None, cache_url=None>
      self.build_url = <local> <bound method HttpUrl.build_url of <http link, base_url=u'http://www.ghostscript.com]', parent_url=u'https://ghostscript.com/irclogs/2014/07/30.html', base_ref=u'http://ghostscript.com/irclogs/', recursion_level=1, url_connection=None, line=32, column=142, page=0, name=u'http://www.ghostscript.co...
  File "/tmp/linkchecker/lib/python/LinkChecker-9.4.0-py2.7-linux-x86_64.egg/linkcheck/checker/urlbase.py", line 361, in build_url
    line: base_url, is_idn = url_norm(self.base_url, self.encoding)
    locals:
      base_url = <not found>
      is_idn = <not found>
      url_norm = <global> <function url_norm at 0x7fbc488a77d0>
      self = <local> <http link, base_url=u'http://www.ghostscript.com]', parent_url=u'https://ghostscript.com/irclogs/2014/07/30.html', base_ref=u'http://ghostscript.com/irclogs/', recursion_level=1, url_connection=None, line=32, column=142, page=0, name=u'http://www.ghostscript.com]', anchor=None, cache_url=None>
      self.base_url = <local> u'http://www.ghostscript.com]', len = 27
      self.encoding = <local> None
  File "/tmp/linkchecker/lib/python/LinkChecker-9.4.0-py2.7-linux-x86_64.egg/linkcheck/checker/urlbase.py", line 75, in url_norm
    line: return urlutil.url_norm(url, encoding=encoding)
    locals:
      urlutil = <global> <module 'linkcheck.url' from '/tmp/linkchecker/lib/python/LinkChecker-9.4.0-py2.7-linux-x86_64.egg/linkcheck/url.pyc'>
      urlutil.url_norm = <global> <function url_norm at 0x7fbc48ae1e60>
      url = <local> u'http://www.ghostscript.com]', len = 27
      encoding = <local> None
  File "/tmp/linkchecker/lib/python/LinkChecker-9.4.0-py2.7-linux-x86_64.egg/linkcheck/url.py", line 314, in url_norm
    line: urlparts = list(urlparse.urlsplit(url))
    locals:
      urlparts = <not found>
      list = <builtin> <type 'list'>
      urlparse = <global> <module 'urlparse' from '/usr/lib/python2.7/urlparse.pyc'>
      urlparse.urlsplit = <global> <function urlsplit at 0x7fbc4a156230>
      url = <local> 'http://www.ghostscript.com]', len = 27
  File "/usr/lib/python2.7/urlparse.py", line 191, in urlsplit
    line: raise ValueError("Invalid IPv6 URL")
    locals:
      ValueError = <builtin> <type 'exceptions.ValueError'>
ValueError: Invalid IPv6 URL
System info:
LinkChecker 9.4.0
Released on: xx.xx.xxxx
Python 2.7.14+ (default, Apr  2 2018, 04:16:25) 
[GCC 7.3.0] on linux2
PYTHONPATH = '/tmp/linkchecker/lib/python:'
Modules: Requests, Pysqlite, Sqlite, Gconf
Local time: 2018-04-18 01:43:00+008
sys.argv: ['/tmp/linkchecker/bin/linkchecker', '-Fhtml', '-r=1', '--verbose', 'https://ghostscript.com/irclogs/2014/07/30.html']
LANGUAGE = 'en_US:en'
LANG = 'en_US.UTF-8'
Default locale: ('en', 'UTF-8')

 ******** LinkChecker internal error, over and out ********
WARNING linkcheck.check 2018-04-18 01:43:00,991 CheckThread-https://ghostscript.com/irclogs/2014/07/30.html internal error occurred
WARNING linkcheck.check 2018-04-18 01:43:00,991 CheckThread-https://ghostscript.com/irclogs/2014/07/30.html internal error occurred

URL        `http://google.com/search'
Parent URL https://ghostscript.com/irclogs/2014/07/30.html, line 23, col 1
Base       http://ghostscript.com/irclogs/
Real URL   http://google.com/search
Info       The URL is outside of the domain filter, checked only
           syntax.
Result     Valid: filtered

URL        `../logo.png'
Parent URL https://ghostscript.com/irclogs/2014/07/30.html, line 11, col 1
Base       http://ghostscript.com/irclogs/
Real URL   http://ghostscript.com/logo.png
Info       The URL is outside of the domain filter, checked only
           syntax.
Result     Valid: filtered

URL        `../logs.css'
Parent URL https://ghostscript.com/irclogs/2014/07/30.html, line 6, col 1
Base       http://ghostscript.com/irclogs/
Real URL   http://ghostscript.com/logs.css
Info       The URL is outside of the domain filter, checked only
           syntax.
Result     Valid: filtered

URL        `2014/07/29.html'
Name       `<<<Back 1 day (to 2014/07/29)'
Parent URL https://ghostscript.com/irclogs/2014/07/30.html, line 29, col 47
Base       http://ghostscript.com/irclogs/
Real URL   https://ghostscript.com/irclogs/2014/07/29.html
Check time 1.105 seconds
Size       12.60KB
Info       Redirected to
           `https://ghostscript.com/irclogs/2014/07/29.html'.
Result     Valid: 200 OK

Statistics:
Downloaded: 70.39KB.
Content types: 0 image, 1 text, 0 video, 0 audio, 0 application, 0 mail and 3 other.
URL lengths: min=24, max=47, avg=33.

That's it. 4 links in 6 URLs checked. 0 warnings found. 0 errors found.
There was 1 internal error.
Stopped checking at 2018-04-18 01:43:02+008 (2 seconds)
```

I noticed the IPv6 error towards the end, but I didn't explicitly specify anything IPv6 related that I know of. If there is more information I can provide let me know and I'll do my best to help you.

**Comment by mgedmin** [comment] 2018-04-17 18:16
The URL in question is `http://www.ghostscript.com]`.  The URL parser in the Python standard library gets confused by the `]` character and thinks it must be a malformed IPv6 URL (these look like `http://[2001:0db8:85a3::8a2e:0370:7334]`).

What we should be doing is catching ValueError exceptions raised by urlparse and reporting them as bad URLs instead of internal errors.

**Comment by cjmayo** [comment] 2020-08-07 18:53
Duplicate of #43.

**Closed by cjmayo** 2020-08-07 18:53 UTC
Labels: bug
