### ISSUE TITLE
Linkchecker - internal error

### ISSUE THREAD

**Issue by sarcanon** [linkchecker/linkchecker#240] opened 2019-04-16 03:09 UTC
## Summary

Got an internal error. Error output below. Actual URL has been obfuscated. Happy to provide actual value, but not in a non-public forum.

## Error report

You have found an internal error in LinkChecker. Please write a bug report at https://github.com/wummel/linkchecker/issues
and include the following information:
- the URL or file you are testing
- the system information below

When using the commandline client:
- your commandline arguments and any custom configuration files.
- the output of a debug run with option "-Dall"

Not disclosing some of the information above due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

<details>
<summary>Traceback</summary>

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/linkcheck/director/checker.py", line 104, in check_url
    line: self.check_url_data(url_data)
    locals:
      self = <local> <Checker(CheckThread-https://stage.example.org/epindex/, started 33510344055872)>
      self.check_url_data = <local> <bound method Checker.check_url_data of <Checker(CheckThread-https://stage.example.org/epindex/, started 33510344055872)>>
      url_data = <local> <https link, base_url=u'/epindex/', parent_url=u'https://stage.example.org/', base_ref=None, recursion_level=1, url_connection=None, line=308, column=33, page=0, name=u'Epigraphic Indexes', anchor=u'', cache_url=https://stage.example.org/epindex/>
  File "/usr/local/lib/python2.7/site-packages/linkcheck/director/checker.py", line 120, in check_url_data
    line: check_url(url_data, self.logger)
    locals:
      check_url = <global> <function check_url at 0x1e79f6ba8578>
      url_data = <local> <https link, base_url=u'/epindex/', parent_url=u'https://stage.example.org/', base_ref=None, recursion_level=1, url_connection=None, line=308, column=33, page=0, name=u'Epigraphic Indexes', anchor=u'', cache_url=https://stage.example.org/epindex/>
      self = <local> <Checker(CheckThread-https://stage.example.org/epindex/, started 33510344055872)>
      self.logger = <local> <linkcheck.director.logger.Logger object at 0x1e799aa05ad0>
  File "/usr/local/lib/python2.7/site-packages/linkcheck/director/checker.py", line 52, in check_url
    line: url_data.check()
    locals:
      url_data = <local> <https link, base_url=u'/epindex/', parent_url=u'https://stage.example.org/', base_ref=None, recursion_level=1, url_connection=None, line=308, column=33, page=0, name=u'Epigraphic Indexes', anchor=u'', cache_url=https://stage.example.org/epindex/>
      url_data.check = <local> <bound method HttpUrl.check of <https link, base_url=u'/epindex/', parent_url=u'https://stage.example.org/', base_ref=None, recursion_level=1, url_connection=None, line=308, column=33, page=0, name=u'Epigraphic Indexes', anchor=u'', cache_url=https://stage.example...
  File "/usr/local/lib/python2.7/site-packages/linkcheck/checker/urlbase.py", line 424, in check
    line: self.local_check()
    locals:
      self = <local> <https link, base_url=u'/epindex/', parent_url=u'https://stage.example.org/', base_ref=None, recursion_level=1, url_connection=None, line=308, column=33, page=0, name=u'Epigraphic Indexes', anchor=u'', cache_url=https://stage.example.org/epindex/>
      self.local_check = <local> <bound method HttpUrl.local_check of <https link, base_url=u'/epindex/', parent_url=u'https://stage.example.org/', base_ref=None, recursion_level=1, url_connection=None, line=308, column=33, page=0, name=u'Epigraphic Indexes', anchor=u'', cache_url=https://stage.example...
  File "/usr/local/lib/python2.7/site-packages/linkcheck/checker/urlbase.py", line 442, in local_check
    line: self.check_connection()
    locals:
      self = <local> <https link, base_url=u'/epindex/', parent_url=u'https://stage.example.org/', base_ref=None, recursion_level=1, url_connection=None, line=308, column=33, page=0, name=u'Epigraphic Indexes', anchor=u'', cache_url=https://stage.example.org/epindex/>
      self.check_connection = <local> <bound method HttpUrl.check_connection of <https link, base_url=u'/epindex/', parent_url=u'https://stage.example.org/', base_ref=None, recursion_level=1, url_connection=None, line=308, column=33, page=0, name=u'Epigraphic Indexes', anchor=u'', cache_url=https://stage.example...
  File "/usr/local/lib/python2.7/site-packages/linkcheck/checker/httpurl.py", line 135, in check_connection
    line: self.send_request(request)
    locals:
      self = <local> <https link, base_url=u'/epindex/', parent_url=u'https://stage.example.org/', base_ref=None, recursion_level=1, url_connection=None, line=308, column=33, page=0, name=u'Epigraphic Indexes', anchor=u'', cache_url=https://stage.example.org/epindex/>
      self.send_request = <local> <bound method HttpUrl.send_request of <https link, base_url=u'/epindex/', parent_url=u'https://stage.example.org/', base_ref=None, recursion_level=1, url_connection=None, line=308, column=33, page=0, name=u'Epigraphic Indexes', anchor=u'', cache_url=https://stage.example...
      request = <local> <PreparedRequest [GET]>
  File "/usr/local/lib/python2.7/site-packages/linkcheck/checker/httpurl.py", line 165, in send_request
    line: self._send_request(request, **kwargs)
    locals:
      self = <local> <https link, base_url=u'/epindex/', parent_url=u'https://stage.example.org/', base_ref=None, recursion_level=1, url_connection=None, line=308, column=33, page=0, name=u'Epigraphic Indexes', anchor=u'', cache_url=https://stage.example.org/epindex/>
      self._send_request = <local> <bound method HttpUrl._send_request of <https link, base_url=u'/epindex/', parent_url=u'https://stage.example.org/', base_ref=None, recursion_level=1, url_connection=None, line=308, column=33, page=0, name=u'Epigraphic Indexes', anchor=u'', cache_url=https://stage.example...
      request = <local> <PreparedRequest [GET]>
      kwargs = <local> {'stream': True, 'verify': True, 'allow_redirects': False, 'timeout': 60}
  File "/usr/local/lib/python2.7/site-packages/linkcheck/checker/httpurl.py", line 172, in _send_request
    line: self._add_ssl_info()
    locals:
      self = <local> <https link, base_url=u'/epindex/', parent_url=u'https://stage.example.org/', base_ref=None, recursion_level=1, url_connection=None, line=308, column=33, page=0, name=u'Epigraphic Indexes', anchor=u'', cache_url=https://stage.example.org/epindex/>
      self._add_ssl_info = <local> <bound method HttpUrl._add_ssl_info of <https link, base_url=u'/epindex/', parent_url=u'https://stage.example.org/', base_ref=None, recursion_level=1, url_connection=None, line=308, column=33, page=0, name=u'Epigraphic Indexes', anchor=u'', cache_url=https://stage.example...
  File "/usr/local/lib/python2.7/site-packages/linkcheck/checker/httpurl.py", line 193, in _add_ssl_info
    line: sock = self._get_ssl_sock()
    locals:
      sock = <not found>
      self = <local> <https link, base_url=u'/epindex/', parent_url=u'https://stage.example.org/', base_ref=None, recursion_level=1, url_connection=None, line=308, column=33, page=0, name=u'Epigraphic Indexes', anchor=u'', cache_url=https://stage.example.org/epindex/>
      self._get_ssl_sock = <local> <bound method HttpUrl._get_ssl_sock of <https link, base_url=u'/epindex/', parent_url=u'https://stage.example.org/', base_ref=None, recursion_level=1, url_connection=None, line=308, column=33, page=0, name=u'Epigraphic Indexes', anchor=u'', cache_url=https://stage.example...
  File "/usr/local/lib/python2.7/site-packages/linkcheck/checker/httpurl.py", line 184, in _get_ssl_sock
    line: if raw_connection.sock is None:
    locals:
      raw_connection = <local> None
      raw_connection.sock = <local> !AttributeError: 'NoneType' object has no attribute 'sock'
      None = <builtin> None
AttributeError: 'NoneType' object has no attribute 'sock'
```

</details>

System info:
LinkChecker 9.3
Released on: 16.7.2014
Python 2.7.16 (default, Apr 11 2019, 12:48:35)
[GCC 4.2.1 Compatible OpenBSD Clang 7.0.1 (tags/RELEASE_701/final)] on openbsd6
Requests: 2.21.0
Modules: Sqlite
Local time: 2019-04-15 19:56:15-007
sys.argv: ['/usr/local/bin/linkchecker', '--user=foo', '--password', '--quiet', '--file-output=csv/utf_8/state-linkcheck.csv', 'https://stage.example.org/']
Default locale: ('C', 'ascii')

 ******** LinkChecker internal error, over and out ********

## Environment

 * Operating system: OpenBSD foo.example.com 6.5 GENERIC.MP#1 amd64
 * Linkchecker version: INFO 2019-04-15 20:06:07,177 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
LinkChecker 9.3 released 16.7.2014
Copyright (C) 2000-2014 Bastian Kleineidam

 * Python version: Python 2.7.16
 * Install method: package
 * Site URL: withheld, provided on request

## Configuration file

No custom config

## Command used to invoke linkchecker

linkchecker --user=foo --password --quiet --file-output=csv/utf_8/stage-linkcheck.csv https://stage.example.org/

## Debug run

aeneas# linkchecker -Dall
DEBUG 2019-04-15 20:03:54,298 MainThread Python 2.7.16 (default, Apr 11 2019, 12:48:35)
[GCC 4.2.1 Compatible OpenBSD Clang 7.0.1 (tags/RELEASE_701/final)] on openbsd6
DEBUG 2019-04-15 20:03:54,299 MainThread reading configuration from ['/root/.linkchecker/linkcheckerrc']
WARNING 2019-04-15 20:03:54,312 MainThread Running as root user; dropping privileges by changing user to nobody.
INFO 2019-04-15 20:03:54,313 MainThread Checking intern URLs only; use --check-extern to check extern URLs.
DEBUG 2019-04-15 20:03:54,321 MainThread configuration: [('aborttimeout', 300),
 ('allowedschemes', []),
 ('authentication', []),
 ('blacklist', {}),
 ('checkextern', False),
 ('cookiefile', None),
 ('csv', {}),
 ('debugmemory', False),
 ('dot', {}),
 ('enabledplugins', []),
 ('externlinks', []),
 ('fileoutput', []),
 ('gml', {}),
 ('gxml', {}),
 ('html', {}),
 ('ignorewarnings', []),
 ('internlinks', []),
 ('localwebroot', None),
 ('logger', 'TextLogger'),
 ('loginextrafields', {}),
 ('loginpasswordfield', 'password'),
 ('loginurl', None),
 ('loginuserfield', 'login'),
 ('maxfilesizedownload', 5242880),
 ('maxfilesizeparse', 1048576),
 ('maxhttpredirects', 10),
 ('maxnumurls', None),
 ('maxrequestspersecond', 10),
 ('maxrunseconds', None),
 ('nntpserver', None),
 ('none', {}),
 ('output', 'text'),
 ('pluginfolders', []),
 ('proxy', {}),
 ('quiet', False),
 ('recursionlevel', -1),
 ('sitemap', {}),
 ('sql', {}),
 ('sslverify', True),
 ('status', True),
 ('status_wait_seconds', 5),
 ('text', {}),
 ('threads', 10),
 ('timeout', 60),
 ('trace', False),
 ('useragent',
  u'Mozilla/5.0 (compatible; LinkChecker/9.3; +http://wummel.github.io/linkchecker/)'),
 ('verbose', False),
 ('warnings', True),
 ('xml', {})]
WARNING 2019-04-15 20:03:54,323 MainThread no files or URLs given
LinkChecker 9.3              Copyright (C) 2000-2014 Bastian Kleineidam
LinkChecker comes with ABSOLUTELY NO WARRANTY!
This is free software, and you are welcome to redistribute it
under certain conditions. Look at the file `LICENSE' within this
distribution.
Get the newest version at http://wummel.github.io/linkchecker/
Write comments and bugs to https://github.com/wummel/linkchecker/issues
Support this project at http://wummel.github.io/linkchecker/donations.html

Start checking at 2019-04-15 20:03:54-007

Statistics:
Downloaded: 0B.
No statistics available since no URLs were checked.

That's it. 0 links in 0 URLs checked. 0 warnings found. 0 errors found.
Stopped checking at 2019-04-15 20:03:54-007 (0.00 seconds)

**Comment by mgedmin** [comment] 2019-04-16 07:17
> AttributeError: 'NoneType' object has no attribute 'sock'

This looks like a duplicate of #76.  We've a fix committed to git, but we've been unable to push fixed releases to PyPI due to the previous maintainer being missing in action (see #4).

**Comment by ndbroadbent** [comment] 2019-11-15 08:12
Hello, I'm also running into this error. Would it be possible to release a new PyPI package under a new name?

**Comment by cjmayo** [comment] 2020-08-07 15:33
If it wasn't fixed in git do open a new issue (with a minimal example of the problem).

**Closed by cjmayo** 2020-08-07 15:33 UTC
